### ISSUE TITLE
Analyzing data from Neuropixels 2.0 with 4 shanks

### ISSUE THREAD

**Issue by ja-94** [SpikeInterface/spikeinterface#1923]
Hi,

I'm using 2.0 Neuropixel probes with 4 shanks. Following the ['Analyze Neuropixels datasets'](https://spikeinterface.readthedocs.io/en/latest/how_to/analyse_neuropixels.html) tutorial I see that `si.plot_probe_map(raw_rec, ax=ax, with_channel_ids=True)` produces a plot with the wrong channel mapping, where all channels appear on the first shank, even though the four shanks are plotted. 

![WrongChannelMap](https://github.com/SpikeInterface/probeinterface/assets/38291173/a1f39a8a-4c19-4564-825f-2e9f37fd99a7)

With `ax.set_ylim(-50, 3000)`:

![WrongChannelMap](https://github.com/SpikeInterface/probeinterface/assets/38291173/d83d06cd-fdb3-4162-a220-21711201af64)

According to [this](https://github.com/SpikeInterface/probeinterface/issues/185) issue the problem with plotting 4 shank probes was solved by upgrading to version 0.97.1, but I'm running version 0.99.0.dev0 and something similar is happening. 

I run the whole tutorial and the shanks are being represented as a single one on the sortingview widget as well, so I guess they are just being treated as a single shank throughout the tutorial?

What is recommended for these probes? Should I just split the files into one per shank and analyze them separately like [here](https://github.com/SpikeInterface/spikeinterface/issues/1666), or is there a way to treat them as a single probe with four shanks?

Thanks!!

**Comment by ckwalters** [comment]
Seconding this issue with 4-shank np probes. The channel sites had been mapped correctly when viewing kilosort output in phy with an older version of spikeinterface that I was running, but this was broken when I updated.

**Comment by alejoe91** [comment]
Hi guys, can you try to install `probeinterface` from the main branch? I believe this has been fixed here: https://github.com/SpikeInterface/probeinterface/pull/205

**Comment by ja-94** [comment]
Hi @alejoe91 ,  

Thanks for your reply!

I tried erasing the older folder and re-installing with these commands:

```
git clone https://github.com/SpikeInterface/spikeinterface.git
cd spikeinterface
pip install -e .
cd ..
```

Still getting the same plot, not sure if I did something wrong.

**Comment by ckwalters** [comment]
Thanks Alessio, this worked for me! Had to call `pip install git+https://github.com/SpikeInterface/probeinterface.git` inside my conda env (in case anyone runs into same issue).
